[aws]
disabled = true

[gcloud]
disabled = true

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[character]
success_symbol = "ğŸš€"
error_symbol = "ğŸ’©"

[directory]
fish_style_pwd_dir_length = 1

[git_branch]
symbol = "ï˜ "

[git_commit]
only_detached=false

[git_state]
format = '\([$state( $progress_current of $progress_total)]($style)\) '
cherry_pick = "ğŸ’ PICKING"
merge = "îœ§ MERGING"

[cmd_duration]
min_time=300

[nodejs]
symbol="îœ˜ "

[python]
symbol="îˆµ "

[ruby]
symbol="îœ¹ "

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = "%R"
style = "yellow"
