[aws]
displayed_items="profile"
symbol = "îŒ½ "

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[character]
symbol = "ğŸš€"
error_symbol = "ğŸ’©"
use_symbol_for_status = true

[directory]
fish_style_pwd_dir_length = 1

[git_branch]
symbol = "ï˜ "

[git_commit]
only_detached=false

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"
merge = "îœ§ MERGING"

[cmd_duration]
min_time=300

[hostname]
prefix = "âŸª"
suffix = "âŸ«"

[nodejs]
symbol="îœ˜ "

[python]
symbol="îˆµ "

[ruby]
symbol="îœ¹ "

[time]
disabled = false
format = "[%R]"
style = "yellow"
